# Generated by Django 3.2 on 2021-04-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskbord', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='status',
            field=models.CharField(choices=[(1, 'New'), (2, 'In Progress'), (3, 'In QA'), (4, 'Ready'), (5, 'Done')], default='New', max_length=1),
        ),
    ]
